[package]
name = "nurl"
version = "0.3.12"
authors = ["figsoda <figsoda@pm.me>"]
edition = "2021"
description = "Generate Nix fetcher calls from repository URLs"
readme = "README.md"
homepage = "https://github.com/nix-community/nurl"
repository = "https://github.com/nix-community/nurl"
license = "MPL-2.0"
keywords = ["cli", "fetch", "git", "nix", "prefetch"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0.71"
bstr = "1.6.0"
data-encoding = "2.4.0"
enum_dispatch = "0.3.12"
gix-url = "0.20.1"
is-terminal = "0.4.9"
itertools = "0.11.0"
nix-compat = { git = "https://code.tvl.fyi/depot.git:/tvix/nix-compat.git" }
once_cell = "1.18.0"
owo-colors = { version = "3.5.0", features = ["supports-colors"] }
rustc-hash = "1.1.0"
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.100"
ureq = { version = "2.7.1", features = ["json"] }

[dependencies.clap]
version = "4.3.11"
features = ["cargo", "derive", "unicode", "wrap_help"]

[build-dependencies]
clap = { version = "4.3.11", features = ["derive"] }
clap_complete = "4.3.2"
clap_mangen = "0.2.12"

[dev-dependencies]
assert_cmd = "2.0.11"
nu-glob = "0.82.0"
trycmd = "0.14.16"

[profile.release]
lto = true
panic = "abort"
codegen-units = 1
